<?php

namespace app\api\controller\v2;
use think\Request;

class Index {
  public function index(Request $request) {
    $data = $request->param();
    $arr  = array(
      [
        "movie_id"   => '10001',
        "movie_name" => "荞麦疯长",
        "Image"      => "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p480747492.webp",
        'director'   => "徐展雄",
        "bianju"     => "徐展雄",
        "actor"      => "马思纯 / 钟楚曦 / 黄景瑜 / 王砚辉 / 王阳明",
        "movie_type" => "剧情 / 爱情",
        "contry"     => "中国大陆",
        "lan"        => "汉语普通话 / 上海话",
        "start_date" => "2020-08-25(中国大陆) / 2020-07-27(上海电影节)",
        "time_long"  => "112分钟",
        "call_as"    => "Wild Grass",
        "IMDB_link"  => "tt10080092",
      ], [
        "movie_id"   => '10002',
        "movie_name" => "福尔摩斯小姐：失踪的侯爵 Enola Holmes",
        "Image"      => "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2561716440.webp",
        'director'   => "哈利·布拉德比尔",
        "bianju"     => "杰克·索恩 / 南茜·斯普林格",
        "actor"      => "米莉·波比·布朗 / 路易斯·帕特里奇 / 山姆·克拉弗林 / 亨利·卡维尔 / 海伦娜·伯翰·卡特",
        "movie_type" => "剧情 / 悬疑",
        "contry"     => "美国 / 英国",
        "lan"        => "英语",
        "start_date" => "2020-09-23(美国/中国大陆网络)",
        "time_long"  => "123分钟",
        "call_as"    => "福尔摩斯小姐 / 福尔摩斯小姐：消失的侯爵 / 天才少女福爾摩斯(台) / 福尔摩斯小妹 / 福尔摩斯小妹探案 / 女福尔摩斯 / The Enola Holmes Mysteries",
        "IMDB_link"  => "tt7846844",
      ], [
        "movie_id"   => '10003',
        "movie_name" => "荞麦疯长",
        "Image"      => "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p457760035.webp",
        'director'   => "徐展雄",
        "bianju"     => "徐展雄",
        "actor"      => "马思纯 / 钟楚曦 / 黄景瑜 / 王砚辉 / 王阳明",
        "movie_type" => "剧情 / 爱情",
        "contry"     => "中国大陆",
        "lan"        => "汉语普通话 / 上海话",
        "start_date" => "2020-08-25(中国大陆) / 2020-07-27(上海电影节)",
        "time_long"  => "112分钟",
        "call_as"    => "Wild Grass",
        "IMDB_link"  => "tt10080092",
      ], [
        "movie_id"   => '10004',
        "movie_name" => "荞麦疯长",
        "Image"      => "https://img2.doubanio.com/view/photo/s_ratio_poster/public/p2578474613.webp",
        'director'   => "徐展雄",
        "bianju"     => "徐展雄",
        "actor"      => "马思纯 / 钟楚曦 / 黄景瑜 / 王砚辉 / 王阳明",
        "movie_type" => "剧情 / 爱情",
        "contry"     => "中国大陆",
        "lan"        => "汉语普通话 / 上海话",
        "start_date" => "2020-08-25(中国大陆) / 2020-07-27(上海电影节)",
        "time_long"  => "112分钟",
        "call_as"    => "Wild Grass",
        "IMDB_link"  => "tt10080092",
      ], [
        "movie_id"   => '10005',
        "movie_name" => "福尔摩斯小姐：失踪的侯爵 Enola Holmes",
        "Image"      => "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2557573348.webp",
        'director'   => "哈利·布拉德比尔",
        "bianju"     => "杰克·索恩 / 南茜·斯普林格",
        "actor"      => "米莉·波比·布朗 / 路易斯·帕特里奇 / 山姆·克拉弗林 / 亨利·卡维尔 / 海伦娜·伯翰·卡特",
        "movie_type" => "剧情 / 悬疑",
        "contry"     => "美国 / 英国",
        "lan"        => "英语",
        "start_date" => "2020-09-23(美国/中国大陆网络)",
        "time_long"  => "123分钟",
        "call_as"    => "福尔摩斯小姐 / 福尔摩斯小姐：消失的侯爵 / 天才少女福爾摩斯(台) / 福尔摩斯小妹 / 福尔摩斯小妹探案 / 女福尔摩斯 / The Enola Holmes Mysteries",
        "IMDB_link"  => "tt7846844",
      ], [
        "movie_id"   => '10006',
        "movie_name" => "荞麦疯长",
        "Image"      => "https://img2.doubanio.com/view/photo/s_ratio_poster/public/p492406163.webp",
        'director'   => "徐展雄",
        "bianju"     => "徐展雄",
        "actor"      => "马思纯 / 钟楚曦 / 黄景瑜 / 王砚辉 / 王阳明",
        "movie_type" => "剧情 / 爱情",
        "contry"     => "中国大陆",
        "lan"        => "汉语普通话 / 上海话",
        "start_date" => "2020-08-25(中国大陆) / 2020-07-27(上海电影节)",
        "time_long"  => "112分钟",
        "call_as"    => "Wild Grass",
        "IMDB_link"  => "tt10080092",
      ], [
        "movie_id"   => '10007',
        "movie_name" => "荞麦疯长",
        "Image"      => "https://img2.doubanio.com/view/photo/s_ratio_poster/public/p2616355133.webp",
        'director'   => "徐展雄",
        "bianju"     => "徐展雄",
        "actor"      => "马思纯 / 钟楚曦 / 黄景瑜 / 王砚辉 / 王阳明",
        "movie_type" => "剧情 / 爱情",
        "contry"     => "中国大陆",
        "lan"        => "汉语普通话 / 上海话",
        "start_date" => "2020-08-25(中国大陆) / 2020-07-27(上海电影节)",
        "time_long"  => "112分钟",
        "call_as"    => "Wild Grass",
        "IMDB_link"  => "tt10080092",
      ], [
        "movie_id"   => '10008',
        "movie_name" => "福尔摩斯小姐：失踪的侯爵 Enola Holmes",
        "Image"      => "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p524964039.webp",
        'director'   => "哈利·布拉德比尔",
        "bianju"     => "杰克·索恩 / 南茜·斯普林格",
        "actor"      => "米莉·波比·布朗 / 路易斯·帕特里奇 / 山姆·克拉弗林 / 亨利·卡维尔 / 海伦娜·伯翰·卡特",
        "movie_type" => "剧情 / 悬疑",
        "contry"     => "美国 / 英国",
        "lan"        => "英语",
        "start_date" => "2020-09-23(美国/中国大陆网络)",
        "time_long"  => "123分钟",
        "call_as"    => "福尔摩斯小姐 / 福尔摩斯小姐：消失的侯爵 / 天才少女福爾摩斯(台) / 福尔摩斯小妹 / 福尔摩斯小妹探案 / 女福尔摩斯 / The Enola Holmes Mysteries",
        "IMDB_link"  => "tt7846844",
      ], [
        "movie_id"   => '10009',
        "movie_name" => "荞麦疯长",
        "Image"      => "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2574551676.webp",
        'director'   => "徐展雄",
        "bianju"     => "徐展雄",
        "actor"      => "马思纯 / 钟楚曦 / 黄景瑜 / 王砚辉 / 王阳明",
        "movie_type" => "剧情 / 爱情",
        "contry"     => "中国大陆",
        "lan"        => "汉语普通话 / 上海话",
        "start_date" => "2020-08-25(中国大陆) / 2020-07-27(上海电影节)",
        "time_long"  => "112分钟",
        "call_as"    => "Wild Grass",
        "IMDB_link"  => "tt10080092",
      ], [
        "movie_id"   => '10010',
        "movie_name" => "荞麦疯长",
        "Image"      => "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2614988097.webp",
        'director'   => "徐展雄",
        "bianju"     => "徐展雄",
        "actor"      => "马思纯 / 钟楚曦 / 黄景瑜 / 王砚辉 / 王阳明",
        "movie_type" => "剧情 / 爱情",
        "contry"     => "中国大陆",
        "lan"        => "汉语普通话 / 上海话",
        "start_date" => "2020-08-25(中国大陆) / 2020-07-27(上海电影节)",
        "time_long"  => "112分钟",
        "call_as"    => "Wild Grass",
        "IMDB_link"  => "tt10080092",
      ], [
        "movie_id"   => '10011',
        "movie_name" => "福尔摩斯小姐：失踪的侯爵 Enola Holmes",
        "Image"      => "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p479682972.webp",
        'director'   => "哈利·布拉德比尔",
        "bianju"     => "杰克·索恩 / 南茜·斯普林格",
        "actor"      => "米莉·波比·布朗 / 路易斯·帕特里奇 / 山姆·克拉弗林 / 亨利·卡维尔 / 海伦娜·伯翰·卡特",
        "movie_type" => "剧情 / 悬疑",
        "contry"     => "美国 / 英国",
        "lan"        => "英语",
        "start_date" => "2020-09-23(美国/中国大陆网络)",
        "time_long"  => "123分钟",
        "call_as"    => "福尔摩斯小姐 / 福尔摩斯小姐：消失的侯爵 / 天才少女福爾摩斯(台) / 福尔摩斯小妹 / 福尔摩斯小妹探案 / 女福尔摩斯 / The Enola Holmes Mysteries",
        "IMDB_link"  => "tt7846844",
      ], [
        "movie_id"   => '10012',
        "movie_name" => "荞麦疯长",
        "Image"      => "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p579729551.webp",
        'director'   => "徐展雄",
        "bianju"     => "徐展雄",
        "actor"      => "马思纯 / 钟楚曦 / 黄景瑜 / 王砚辉 / 王阳明",
        "movie_type" => "剧情 / 爱情",
        "contry"     => "中国大陆",
        "lan"        => "汉语普通话 / 上海话",
        "start_date" => "2020-08-25(中国大陆) / 2020-07-27(上海电影节)",
        "time_long"  => "112分钟",
        "call_as"    => "Wild Grass",
        "IMDB_link"  => "tt10080092",
      ], [
        "movie_id"   => '10013',
        "movie_name" => "荞麦疯长",
        "Image"      => "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1461851991.webp",
        'director'   => "徐展雄",
        "bianju"     => "徐展雄",
        "actor"      => "马思纯 / 钟楚曦 / 黄景瑜 / 王砚辉 / 王阳明",
        "movie_type" => "剧情 / 爱情",
        "contry"     => "中国大陆",
        "lan"        => "汉语普通话 / 上海话",
        "start_date" => "2020-08-25(中国大陆) / 2020-07-27(上海电影节)",
        "time_long"  => "112分钟",
        "call_as"    => "Wild Grass",
        "IMDB_link"  => "tt10080092",
      ], [
        "movie_id"   => '10014',
        "movie_name" => "福尔摩斯小姐：失踪的侯爵 Enola Holmes",
        "Image"      => "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p1910824951.webp",
        'director'   => "哈利·布拉德比尔",
        "bianju"     => "杰克·索恩 / 南茜·斯普林格",
        "actor"      => "米莉·波比·布朗 / 路易斯·帕特里奇 / 山姆·克拉弗林 / 亨利·卡维尔 / 海伦娜·伯翰·卡特",
        "movie_type" => "剧情 / 悬疑",
        "contry"     => "美国 / 英国",
        "lan"        => "英语",
        "start_date" => "2020-09-23(美国/中国大陆网络)",
        "time_long"  => "123分钟",
        "call_as"    => "福尔摩斯小姐 / 福尔摩斯小姐：消失的侯爵 / 天才少女福爾摩斯(台) / 福尔摩斯小妹 / 福尔摩斯小妹探案 / 女福尔摩斯 / The Enola Holmes Mysteries",
        "IMDB_link"  => "tt7846844",
      ], [
        "movie_id"   => '10015',
        "movie_name" => "荞麦疯长",
        "Image"      => "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2455050536.webp",
        'director'   => "徐展雄",
        "bianju"     => "徐展雄",
        "actor"      => "马思纯 / 钟楚曦 / 黄景瑜 / 王砚辉 / 王阳明",
        "movie_type" => "剧情 / 爱情",
        "contry"     => "中国大陆",
        "lan"        => "汉语普通话 / 上海话",
        "start_date" => "2020-08-25(中国大陆) / 2020-07-27(上海电影节)",
        "time_long"  => "112分钟",
        "call_as"    => "Wild Grass",
        "IMDB_link"  => "tt10080092",
      ], [
        "movie_id"   => '10016',
        "movie_name" => "荞麦疯长",
        "Image"      => "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1363250216.webp",
        'director'   => "徐展雄",
        "bianju"     => "徐展雄",
        "actor"      => "马思纯 / 钟楚曦 / 黄景瑜 / 王砚辉 / 王阳明",
        "movie_type" => "剧情 / 爱情",
        "contry"     => "中国大陆",
        "lan"        => "汉语普通话 / 上海话",
        "start_date" => "2020-08-25(中国大陆) / 2020-07-27(上海电影节)",
        "time_long"  => "112分钟",
        "call_as"    => "Wild Grass",
        "IMDB_link"  => "tt10080092",
      ], [
        "movie_id"   => '10017',
        "movie_name" => "福尔摩斯小姐：失踪的侯爵 Enola Holmes",
        "Image"      => "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p2614500649.webp",
        'director'   => "哈利·布拉德比尔",
        "bianju"     => "杰克·索恩 / 南茜·斯普林格",
        "actor"      => "米莉·波比·布朗 / 路易斯·帕特里奇 / 山姆·克拉弗林 / 亨利·卡维尔 / 海伦娜·伯翰·卡特",
        "movie_type" => "剧情 / 悬疑",
        "contry"     => "美国 / 英国",
        "lan"        => "英语",
        "start_date" => "2020-09-23(美国/中国大陆网络)",
        "time_long"  => "123分钟",
        "call_as"    => "福尔摩斯小姐 / 福尔摩斯小姐：消失的侯爵 / 天才少女福爾摩斯(台) / 福尔摩斯小妹 / 福尔摩斯小妹探案 / 女福尔摩斯 / The Enola Holmes Mysteries",
        "IMDB_link"  => "tt7846844",
      ], [
        "movie_id"   => '10018',
        "movie_name" => "荞麦疯长",
        "Image"      => "https://img2.doubanio.com/view/photo/s_ratio_poster/public/p2564556863.webp",
        'director'   => "徐展雄",
        "bianju"     => "徐展雄",
        "actor"      => "马思纯 / 钟楚曦 / 黄景瑜 / 王砚辉 / 王阳明",
        "movie_type" => "剧情 / 爱情",
        "contry"     => "中国大陆",
        "lan"        => "汉语普通话 / 上海话",
        "start_date" => "2020-08-25(中国大陆) / 2020-07-27(上海电影节)",
        "time_long"  => "112分钟",
        "call_as"    => "Wild Grass",
        "IMDB_link"  => "tt10080092",
      ], [
        "movie_id"   => '10019',
        "movie_name" => "荞麦疯长",
        "Image"      => "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p616779645.webp",
        'director'   => "徐展雄",
        "bianju"     => "徐展雄",
        "actor"      => "马思纯 / 钟楚曦 / 黄景瑜 / 王砚辉 / 王阳明",
        "movie_type" => "剧情 / 爱情",
        "contry"     => "中国大陆",
        "lan"        => "汉语普通话 / 上海话",
        "start_date" => "2020-08-25(中国大陆) / 2020-07-27(上海电影节)",
        "time_long"  => "112分钟",
        "call_as"    => "Wild Grass",
        "IMDB_link"  => "tt10080092",
      ], [
        "movie_id"   => '10020',
        "movie_name" => "福尔摩斯小姐：失踪的侯爵 Enola Holmes",
        "Image"      => "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2540924496.webp",
        'director'   => "哈利·布拉德比尔",
        "bianju"     => "杰克·索恩 / 南茜·斯普林格",
        "actor"      => "米莉·波比·布朗 / 路易斯·帕特里奇 / 山姆·克拉弗林 / 亨利·卡维尔 / 海伦娜·伯翰·卡特",
        "movie_type" => "剧情 / 悬疑",
        "contry"     => "美国 / 英国",
        "lan"        => "英语",
        "start_date" => "2020-09-23(美国/中国大陆网络)",
        "time_long"  => "123分钟",
        "call_as"    => "福尔摩斯小姐 / 福尔摩斯小姐：消失的侯爵 / 天才少女福爾摩斯(台) / 福尔摩斯小妹 / 福尔摩斯小妹探案 / 女福尔摩斯 / The Enola Holmes Mysteries",
        "IMDB_link"  => "tt7846844",
      ], [
        "movie_id"   => '10021',
        "movie_name" => "荞麦疯长",
        "Image"      => "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2614359276.webp",
        'director'   => "徐展雄",
        "bianju"     => "徐展雄",
        "actor"      => "马思纯 / 钟楚曦 / 黄景瑜 / 王砚辉 / 王阳明",
        "movie_type" => "剧情 / 爱情",
        "contry"     => "中国大陆",
        "lan"        => "汉语普通话 / 上海话",
        "start_date" => "2020-08-25(中国大陆) / 2020-07-27(上海电影节)",
        "time_long"  => "112分钟",
        "call_as"    => "Wild Grass",
        "IMDB_link"  => "tt10080092",
      ], [
        "movie_id"   => '10022',
        "movie_name" => "荞麦疯长",
        "Image"      => "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p501177648.webp",
        'director'   => "徐展雄",
        "bianju"     => "徐展雄",
        "actor"      => "马思纯 / 钟楚曦 / 黄景瑜 / 王砚辉 / 王阳明",
        "movie_type" => "剧情 / 爱情",
        "contry"     => "中国大陆",
        "lan"        => "汉语普通话 / 上海话",
        "start_date" => "2020-08-25(中国大陆) / 2020-07-27(上海电影节)",
        "time_long"  => "112分钟",
        "call_as"    => "Wild Grass",
        "IMDB_link"  => "tt10080092",
      ], [
        "movie_id"   => '10023',
        "movie_name" => "福尔摩斯小姐：失踪的侯爵 Enola Holmes",
        "Image"      => "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p1454261925.webp",
        'director'   => "哈利·布拉德比尔",
        "bianju"     => "杰克·索恩 / 南茜·斯普林格",
        "actor"      => "米莉·波比·布朗 / 路易斯·帕特里奇 / 山姆·克拉弗林 / 亨利·卡维尔 / 海伦娜·伯翰·卡特",
        "movie_type" => "剧情 / 悬疑",
        "contry"     => "美国 / 英国",
        "lan"        => "英语",
        "start_date" => "2020-09-23(美国/中国大陆网络)",
        "time_long"  => "123分钟",
        "call_as"    => "福尔摩斯小姐 / 福尔摩斯小姐：消失的侯爵 / 天才少女福爾摩斯(台) / 福尔摩斯小妹 / 福尔摩斯小妹探案 / 女福尔摩斯 / The Enola Holmes Mysteries",
        "IMDB_link"  => "tt7846844",
      ], [
        "movie_id"   => '10024',
        "movie_name" => "荞麦疯长",
        "Image"      => "https://img1.doubanio.com/view/photo/s_ratio_poster/public/p1505392928.webp",
        'director'   => "徐展雄",
        "bianju"     => "徐展雄",
        "actor"      => "马思纯 / 钟楚曦 / 黄景瑜 / 王砚辉 / 王阳明",
        "movie_type" => "剧情 / 爱情",
        "contry"     => "中国大陆",
        "lan"        => "汉语普通话 / 上海话",
        "start_date" => "2020-08-25(中国大陆) / 2020-07-27(上海电影节)",
        "time_long"  => "112分钟",
        "call_as"    => "Wild Grass",
        "IMDB_link"  => "tt10080092",
      ], [
        "movie_id"   => '10025',
        "movie_name" => "荞麦疯长",
        "Image"      => "https://img2.doubanio.com/view/photo/s_ratio_poster/public/p462657443.webp",
        'director'   => "徐展雄",
        "bianju"     => "徐展雄",
        "actor"      => "马思纯 / 钟楚曦 / 黄景瑜 / 王砚辉 / 王阳明",
        "movie_type" => "剧情 / 爱情",
        "contry"     => "中国大陆",
        "lan"        => "汉语普通话 / 上海话",
        "start_date" => "2020-08-25(中国大陆) / 2020-07-27(上海电影节)",
        "time_long"  => "112分钟",
        "call_as"    => "Wild Grass",
        "IMDB_link"  => "tt10080092",
      ], [
        "movie_id"   => '10026',
        "movie_name" => "福尔摩斯小姐：失踪的侯爵 Enola Holmes",
        "Image"      => "https://img3.doubanio.com/view/photo/s_ratio_poster/public/p2513253791.webp",
        'director'   => "哈利·布拉德比尔",
        "bianju"     => "杰克·索恩 / 南茜·斯普林格",
        "actor"      => "米莉·波比·布朗 / 路易斯·帕特里奇 / 山姆·克拉弗林 / 亨利·卡维尔 / 海伦娜·伯翰·卡特",
        "movie_type" => "剧情 / 悬疑",
        "contry"     => "美国 / 英国",
        "lan"        => "英语",
        "start_date" => "2020-09-23(美国/中国大陆网络)",
        "time_long"  => "123分钟",
        "call_as"    => "福尔摩斯小姐 / 福尔摩斯小姐：消失的侯爵 / 天才少女福爾摩斯(台) / 福尔摩斯小妹 / 福尔摩斯小妹探案 / 女福尔摩斯 / The Enola Holmes Mysteries",
        "IMDB_link"  => "tt7846844",
      ], [
        "movie_id"   => '10027',
        "movie_name" => "荞麦疯长",
        "Image"      => "https://img2.doubanio.com/view/photo/s_ratio_poster/public/p452089833.webp",
        'director'   => "徐展雄",
        "bianju"     => "徐展雄",
        "actor"      => "马思纯 / 钟楚曦 / 黄景瑜 / 王砚辉 / 王阳明",
        "movie_type" => "剧情 / 爱情",
        "contry"     => "中国大陆",
        "lan"        => "汉语普通话 / 上海话",
        "start_date" => "2020-08-25(中国大陆) / 2020-07-27(上海电影节)",
        "time_long"  => "112分钟",
        "call_as"    => "Wild Grass",
        "IMDB_link"  => "tt10080092",
      ], [
        "movie_id"   => '10028',
        "movie_name" => "荞麦疯长",
        "Image"      => "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2614500706.webp",
        'director'   => "徐展雄",
        "bianju"     => "徐展雄",
        "actor"      => "马思纯 / 钟楚曦 / 黄景瑜 / 王砚辉 / 王阳明",
        "movie_type" => "剧情 / 爱情",
        "contry"     => "中国大陆",
        "lan"        => "汉语普通话 / 上海话",
        "start_date" => "2020-08-25(中国大陆) / 2020-07-27(上海电影节)",
        "time_long"  => "112分钟",
        "call_as"    => "Wild Grass",
        "IMDB_link"  => "tt10080092",
      ], [
        "movie_id"   => '10029',
        "movie_name" => "福尔摩斯小姐：失踪的侯爵 Enola Holmes",
        "Image"      => "https://img9.doubanio.com/view/photo/s_ratio_poster/public/p2614500706.webp",
        'director'   => "哈利·布拉德比尔",
        "bianju"     => "杰克·索恩 / 南茜·斯普林格",
        "actor"      => "米莉·波比·布朗 / 路易斯·帕特里奇 / 山姆·克拉弗林 / 亨利·卡维尔 / 海伦娜·伯翰·卡特",
        "movie_type" => "剧情 / 悬疑",
        "contry"     => "美国 / 英国",
        "lan"        => "英语",
        "start_date" => "2020-09-23(美国/中国大陆网络)",
        "time_long"  => "123分钟",
        "call_as"    => "福尔摩斯小姐 / 福尔摩斯小姐：消失的侯爵 / 天才少女福爾摩斯(台) / 福尔摩斯小妹 / 福尔摩斯小妹探案 / 女福尔摩斯 / The Enola Holmes Mysteries",
        "IMDB_link"  => "tt7846844",
      ], [
        "movie_id"   => '10030',
        "movie_name" => "荞麦疯长",
        "Image"      => "https://img2.doubanio.com/view/photo/s_ratio_poster/public/p452089833.webp",
        'director'   => "徐展雄",
        "bianju"     => "徐展雄",
        "actor"      => "马思纯 / 钟楚曦 / 黄景瑜 / 王砚辉 / 王阳明",
        "movie_type" => "剧情 / 爱情",
        "contry"     => "中国大陆",
        "lan"        => "汉语普通话 / 上海话",
        "start_date" => "2020-08-25(中国大陆) / 2020-07-27(上海电影节)",
        "time_long"  => "112分钟",
        "call_as"    => "Wild Grass",
        "IMDB_link"  => "tt10080092",
      ],
    );
    //$ret_code['page_size']    = $data['pagesize'];
    //$ret_code['page_index']   = $data['pageindex'];
    $ret_code['page_size']    = $data['pagesize'];
    $ret_code['page_index']   = $data['pageindex'];
    $ret_code['record_count'] = count($arr, COUNT_NORMAL);
    $ret_code['subjects']     = $this->pageArray($ret_code['page_size'], $ret_code['page_index'], $arr, 0);
    return json_encode($ret_code);
  }

  /**
   * 数组分页函数  核心函数  array_slice
   * 用此函数之前要先将数据库里面的所有数据按一定的顺序查询出来存入数组中
   * @param integer $count 每页多少条数据
   * @param string $page 当前第几页
   * @param array $array 查询出来的所有数组
   * @param integer $order 0 - 不变 1- 反序
   * @return void 返回数据的数组
   */
  public function pageArray(int $count, string $page, array $array, int $order = 0) {
    global $countpage; #定全局变量
    $page  = (empty($page)) ? '1' : $page; #判断当前页面是否为空 如果为空就表示为第一页面
    $start = ($page - 1) * $count; #计算每次分页的开始位置
    if ($order == 1) {
      $array = array_reverse($array);
    }
    $totals    = count($array);
    $countpage = ceil($totals / $count); #计算总页面数
    $pagedata  = array();
    $pagedata  = array_slice($array, $start, $count);
    return $pagedata; #返回查询数据
  }
}